- routes/api/auth/auth.controller.js
> feature: register api 수정

- controller/together.controller.js
- data/together.js
- routes/together.js
> Merge: 친바하기 생성 api 완료

- controller/together.controller.js
- data/together.js
> Merge: 친바하기 삭제 api

- app.js
- controller/auth.controller.js
- controller/together.controller.js
- data/together.js
- middleware/auth.js
- routes/together.js
> Merge: 친바 조회, 상세조회 api OK, 라우터 수정

- controller/together.controller.js
- data/together.js
- routes/together.js
> Merge: 친바 참석, 삭제 api

- controller/together.controller.js
- data/together.js
- routes/together.js
> Merge: 친바 랜덤매칭 api OK

- controller/together.controller.js
> Merge: 매칭 예외처리

- controller/together.controller.js
- data/together.js
> Merge: 팀 매칭시 데이터 가공해서 보내주기.

- controller/together.controller.js
teamId로 객체에서 배열 그룹화해서 보내주는부분
중복되어서 함수로 빼냄
matching 시에도 팀결과 리턴
> #35 팀매칭시에도 결과보여주기

- .gitignore
- controller/auth.controller.js
- controller/together.controller.js
- package-lock.json
- package.json
- routes/auth.js
> Merge: Issue/39 

- app.js
- controller/auth.controller.js
- package.json
- routes/auth.js
> Merge: Dev app.js

- controller/together.controller.js
- data/together.js
- routes/together.js
> Merge: post matching api 권한주기

- controller/auth.controller.js
- controller/together.controller.js
- data/auth.js
- data/together.js
- middleware/auth.js
- routes/auth.js
> Merge: feat:유저 필드변경 및 친바 삭제 기능 수정

- app.js
- config.js
- controller/board.controller.js
- data/board.js
> Merge: fix: 게시글 생성시 이미지 저장

- .gitignore
- config.js
- controller/board.controller.js
- data/board.js
- package-lock.json
- package.json
- routes/board.js
- s3.js
- s3에 이미지 업로드 및 삭제
- 디비에 이미지 업로드 및 삭제
> Merge: Issue/61

- controller/board.controller.js
- controller/together.controller.js
- data/board.js
- 팀매칭시 0 막음
- 게시글 생성시 참석자리스트에 없는 유저가 들어오면
1. 유저검증
2. 없는 유저면 400에러와 함께 "없는 유저입니다" 리턴
> Merge: fix: #65 팀매칭 팀개수 0 , 게시글 생성시 참석자검증

- controller/board.controller.js
- data/board.js
> fix: 게시판 전체 조회시 모든 이미지 가져오기

- app.js
- config.js
- controller/slack.controller.js
- controller/together.controller.js
- data/together.js
- package-lock.json
- package.json
- routes/slack.js
이벤트 생성, 팀 매칭시 집현전 채널로 슬랙봇 알람전송
> #72 feat: 이벤트 생성, 팀 매칭시 집현전 채널로 슬랙봇 알람전송

- data/board.js
사진, 동영상 구분을 위해
image / video 타입 구분
> Merge: FIX: 이미지 타입도 보여주기

- src/controller/board.controller.js
- src/data/user.js
슬랙 ID가 없더라도 슬랙 알림만 가지 않고 게시글이 작성되도록 수정했습니다!!
직장과 과제 병행하시느라 바쁘신 와중에도 코드 리뷰 진행해주셔서 정말 감사드립니다 😁
> Feature : 친스타그램 게시글에 댓글이 달리면 슬랙 메세지가 오도록 수정 (코드 수정 완료)

- .eslintrc.yml
- .prettierrc
- src/app.js
- src/config/winston.js
- src/controller/board.controller.js
- src/controller/together.controller.js
- src/data/auth.js
- src/data/board.js
- src/data/timeline.js
- src/data/together.js
- src/middleware/uploads.js
- src/routes/board.routes.js
- src/routes/timeline.routes.js
- src/utils/rotation.together.js
eslint 및 prettier 설정을 일치시키고 모두 공유하기 위해 `.prettierrc` 파일을 추가 했습니다
> Issue/139 eslint 및 prettier 설정

- src/app.js
- src/controller/auth.controller.js
- src/controller/together.controller.js
- src/data/together.js
- src/routes/together.routes.js
- yarn.lock
test 브랜치에는 적용되지 않은 main 브랜치의 변경 사항을 test 브랜치에도 적용하기 위해, main과 merge한 test 브랜치를 새로운 브랜치로 복사하여, 원격 저장소에 PR 올립니다(test 브랜치로 바로 push를 할 수 없어서...)
지난 번 PR 리뷰에서, Main으로 바로 머지가 된 부분을 확인하고 리뷰를 했어야 했는데, 확인하지 않고 바로 승인하여 브랜치가 조금 꼬이게 된 것 같아요... 신경쓰지 못한 점 죄송합니다...
> merge: main 브랜치의 변경 사항을 test에도 적용

- src/config.js
- src/db/database.js
test 환경에서 변경된 DB의 포트가 config 파일에 추가되지 않아 API 요청을 실패하던 문제를 해결했습니다.
> fix: add db port

- src/app.js
- src/controller/together.controller.js
- src/data/together.js
Reverts Together42/backend#174
test 브랜치에 먼저 적용 후,  main으로 옮기겠습니다.
> Revert "hotfix: 주간회의 안 닫히는 오류 수정"

- .github/workflows/deploy-main.yml
- .github/workflows/deploy-test.yml
- src/config.js
- src/controller/board.controller.js
- src/middleware/uploads.js
- src/s3.js
tkim님 S3에서 kyungsle님 S3로 이미지들을 이전했습니다.
- S3 이름이 변경됨에 따라 DB image_info 테이블의 filePath를 변경
- filePath에 S3를 그대로 넣지 않고 환경변수로 빼는 방법을 생각중
> feat: S3 이전

- src/app.js
- src/controller/rotation.controller.js
- src/utils/rotation.calendar.js
getTodayDate 함수가 반환하는 값이 string이고, getFourthWeekdaysOfMonth 함수가 반환하는 값이 number다 보니, 타입 매칭 오류로 인해 발생한 문제였습니다.
배열에 있는 값이 string인줄 알았네요... 흑... 수정 내용 바로 올립니다!!
> hotfix : 사서 로테이션 참석 불가 수정

- src/app.js
- src/controller/rotation.controller.js
사서 로테이션에서 슬랙에 전송되는 메세지를 수정했습니다. 제가 잘못 알고 텍스트에 붙여놓은 부분이 있어, 지금 상태라면 아주 못생기게 나올 것 같습니다...
> modify: 사서 로테이션 커밋 메세지 수정

- src/controller/rotation.controller.js
- src/utils/rotation.together.js
> merge test to main

- src/controller/rotation.controller.js
- src/utils/rotation.calendar.js
- src/utils/rotation.together.js
사서 업무 신청 기간을 변경한 test 브랜치의 업데이트 사항을 main 브랜치에 머지합니다
> merge main to test

- src/app.js
- src/controller/rotation.controller.js
- src/data/rotation.js
- src/data/user.js
- src/utils/slack.service.js
로테이션 만료 메세지 보낼 때 사서들에게 배정 날짜를 DM으로 보내줍니다.
> Issue/202 사서 날짜 슬랙봇 전송

- src/app.js
- src/controller/together.controller.js
- src/data/auth.js
> feat: 주간회의 대신 주간식사 자동 생성 및 매칭
